// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvQgq70x-UQDoH_jks4DaIXupXcnqjIY',
    appId: '1:206558481978:web:f6b1130fa03d8135d36f03',
    messagingSenderId: '206558481978',
    projectId: 'authdemo-224e7',
    authDomain: 'authdemo-224e7.firebaseapp.com',
    storageBucket: 'authdemo-224e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeaZQtVJhbNVl24WDlq3VjtZgxZ8oKfX8',
    appId: '1:206558481978:android:b886226ea1e79465d36f03',
    messagingSenderId: '206558481978',
    projectId: 'authdemo-224e7',
    storageBucket: 'authdemo-224e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuq41pwPG3InYP_Fm02kGJcC2UqXRuhuo',
    appId: '1:206558481978:ios:a1de3cdd4aa966b9d36f03',
    messagingSenderId: '206558481978',
    projectId: 'authdemo-224e7',
    storageBucket: 'authdemo-224e7.firebasestorage.app',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuq41pwPG3InYP_Fm02kGJcC2UqXRuhuo',
    appId: '1:206558481978:ios:a1de3cdd4aa966b9d36f03',
    messagingSenderId: '206558481978',
    projectId: 'authdemo-224e7',
    storageBucket: 'authdemo-224e7.firebasestorage.app',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDvQgq70x-UQDoH_jks4DaIXupXcnqjIY',
    appId: '1:206558481978:web:c03f7f14122778cfd36f03',
    messagingSenderId: '206558481978',
    projectId: 'authdemo-224e7',
    authDomain: 'authdemo-224e7.firebaseapp.com',
    storageBucket: 'authdemo-224e7.firebasestorage.app',
  );
}
